### ISSUE TITLE
Test Failure warnings

### ISSUE THREAD

**Issue by schreuderjo** [willowtreeapps/react-sapling#26]
Currently if the test files are written with errors the 'npm test' script will just run indefinitely without actually doing anything.  Not sure what's happening here but maybe we need some linting on the test files as well? Some indication that the test files are failing.

**Comment by trevorsenior** [comment]
Linting does capture the test files now as of b324ea789553d62e5dd9bba97c84442c81ad12f4. This may no longer be an issue.

**Comment by trevorsenior** [comment]
Closing for now. If it's an issue in the future we can reopen it.
