### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by schreuderjo** [willowtreeapps/react-sapling#27]
If we want to have sapling be a development playground it would be nice to have some linting in place along with hot reloading.  It will make things a lot smoother.  Error tracking is pretty manual at this point.

**Comment by trevorsenior** [comment]
- [x] hot reloading (#1)
  - [ ] linting

Linting will come as an addition to the production & development webpack configurations. If there are tslint/eslint errors in the production webpack configurations it should not complete the build.

**Comment by trevorsenior** [comment]
Giving this further thought with @DavidBrear's input, this is something that may vary from user to user in terms of styling of the react-components. If we're already providing component projects with `.eslintrc`  and `tlint.json` files (to satisfy editors), we should reach out into the component project and use the project's configuration for linting vs. and internal linting config.

**Comment by schreuderjo** [comment]
Yeah I agree.  Customized linting rules makes the most sense.  The only downside is having to get that set up for each individual project.  Might not be as bad as I think though.  I'm going to try and implement something on flopdown and see how it goes.
