### ISSUE TITLE
Dev dependencies failing on npm test

### ISSUE THREAD

**Issue by schreuderjo** [willowtreeapps/react-sapling#44]
When I pull in enzyme or sinon.js and try to run npm test I get a ton of errors that all look more or less like this.  

WARNING in ../~/sinon/lib/sinon/assert.js
Critical dependencies:
216:25-32 require function is used in a way in which dependencies cannot be statically extracted
 @ ../~/sinon/lib/sinon/assert.js 216:25-32

It seems like there is an error for every file that it tries to load.

**Comment by schreuderjo** [comment]
Looks like someone else has reported this issue here: https://github.com/airbnb/enzyme/issues/47

**Comment by schreuderjo** [comment]
The sinon.js bug might be unrelated

**Comment by trevorsenior** [comment]
Closing this for now.
