### ISSUE TITLE
Getting started with typescript

### ISSUE THREAD

**Issue by kaw2k** [willowtreeapps/react-sapling#69]
Just some thoughts. 

When you first start a typescript project, the second you break something (like the `projectName`) property, you have to fix it in 3 files (example, root, and test). Perhaps we want to simplify how our default test functions so we can remove that overhead for initial users? 

The test could be as simple as asserting true = true. The idea is to reduce as much friction as possible when first starting. Ideas (pick and choose all, none, or some):

1. Have a default component without any props. The first thing any user would do is to change this, so why have it there to begin with? Welcome to the app, boom, here are errors if you want to do useful things. 
2. Make the initial test as dumb as possible. Or perhaps comment out the test body that way users can see how we could test things.

**Comment by trevorsenior** [comment]
> Have a default component without any props.

It's true the starting example code is a bit over-complex. Most users who are will be starting out with this project already know how to develop React components so a bare minimum react component is probably the best route for both React & TypeScript projects. 

> Make the initial test as dumb as possible.

I'm on board with this as well. I think a simple test that checks if the imported thing is a React component (or something super basic) will do fine.
